---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]

suites:
- name: tuivai
  run_list:
    - recipe[bricks]
  attributes:
    bricks:
      codename: tuivai
- name: mora
  run_list:
    - recipe[bricks]
  attributes:
    bricks:
      codename: mora
- name: dakatua
  run_list:
    - recipe[bricks]
  attributes:
    bricks:
      codename: dakatua
- name: barak
  run_list:
  - recipe[bricks]
  attributes:
    bricks:
      codename: barak
- name: atrai
  run_list:
  - recipe[bricks]
  attributes:
    bricks:
      codename: atrai
- name: phalgu
  run_list:
    - recipe[bricks]
  attributes:
    bricks:
      codename: phalgu
